
spring:
  profiles:
    active: local

  messages:
    basename: i18n/post
    encoding: UTF-8

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true

---

spring:
  config:
    activate:
      on-profile: local

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/template
    username: root
    password: 1234

server:
  address: localhost
  port: 8080

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql: DEBUG
